//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace techtalk2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTable
    {
        public int ID { get; set; }
        public string Ename { get; set; }
        public string Pname { get; set; }
        public string Edes { get; set; }
        public System.DateTime Edate { get; set; }
        public bool isPassed { get; set; }
    }
}
